sudo: no
dist: trusty
language: python
python:
  - "2.7"
  - "3.6"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install coveralls
  - pip install pyyaml
# command to run tests
script:
  - export PATH=${PWD}:${PATH}
  - coverage run -a tests/test_date_time.py
  - coverage run -a tests/test_finger.py
  - coverage report
after_success:
# upload test report
  - coveralls
